import type { InspirationSuggestion } from "./templateTypes";

export type Season = "spring"|"summer"|"fall"|"winter";
const all=["couple","friends","travel","family","roommates","adventure","school","gaming","creative","blank"] as const;
const seasonal=(season:Season,id:string,title:string,description:string,templateId:InspirationSuggestion["templateId"],templateData?:NonNullable<InspirationSuggestion["prefill"]>["templateData"]):InspirationSuggestion=>({id:`season-${season}-${id}`,title,description,templateId,spaceTemplateIds:all,tags:["seasonal",season],season,prefill:{title,description,templateData}});
export const SEASONAL_INSPIRATION:readonly InspirationSuggestion[]=[
  seasonal("spring","garden","Visit a botanical garden","Notice what is beginning again.","activity"),seasonal("spring","picnic","Plan the first picnic of spring","Keep the food easy and choose a patch of sun.","activity"),seasonal("spring","market","Browse a farmers market","Pick one ingredient that looks like the season.","activity"),seasonal("spring","walk","Take a scenic spring walk","Choose a gentle route with something in bloom.","activity"),seasonal("spring","cafe","Sit at an outdoor café","Save somewhere made for a slow, bright afternoon.","coffee",{atmosphere:"Outdoor seating"}),seasonal("spring","home","Start a small spring home project","Choose one corner that would feel good refreshed.","activity"),
  seasonal("summer","beach","Plan an easy beach day","Bring less, stay longer, and save the sunset.","day-trip"),seasonal("summer","kayak","Try kayaking or paddleboarding","Choose calm water and a beginner-friendly rental.","activity"),seasonal("summer","concert","Save an outdoor concert","Keep a summer evening open for live music.","event"),seasonal("summer","camp","Plan a camping night","Start with one night and a short packing list.","camping"),seasonal("summer","fireworks","Find a place to watch fireworks","Save a comfortable viewing spot and an easy exit plan.","event"),seasonal("summer","road","Take a summer road trip","Choose a direction and one stop worth the drive.","day-trip"),seasonal("summer","pool","Plan a pool day","Make room for an uncomplicated afternoon outside.","activity"),
  seasonal("fall","pumpkin","Visit a pumpkin patch","Choose the day for the walk, not just the pumpkins.","activity"),seasonal("fall","apples","Go apple picking","Save an orchard and one recipe for afterward.","activity"),seasonal("fall","hike","Take a fall-color hike","Pick a trail where the view is worth slowing down for.","hike",{bestSeason:"Fall"}),seasonal("fall","haunt","Try a haunted attraction","Choose the level of scary everyone will actually enjoy.","event"),seasonal("fall","cook","Cook something seasonal","Make a warm recipe that leaves good leftovers.","activity"),seasonal("fall","drive","Take a fall scenic drive","Save an overlook, a warm drink, and plenty of daylight.","day-trip",{idealSeason:"Fall"}),
  seasonal("winter","lights","See winter lights","Choose a walkable display and bring something warm.","activity"),seasonal("winter","market","Browse a seasonal market","Go for the atmosphere and choose one thoughtful thing.","activity"),seasonal("winter","cabin","Save a quiet cabin weekend","Find somewhere made for staying in.","hotel",{amenities:["A cozy common space"]}),seasonal("winter","movies","Plan a movie marathon","Choose a theme and leave room to change the lineup.","movie"),seasonal("winter","bake","Have a baking night","Pick something forgiving and share the extras.","activity"),seasonal("winter","skate","Try ice skating","Choose a relaxed public session and warm up afterward.","activity"),seasonal("winter","new-year","Plan a gentle New Year check-in","Collect a few hopes without turning them into pressure.","custom")
];
export function seasonForDate(date=new Date()):Season{const month=date.getMonth()+1;if(month>=3&&month<=5)return"spring";if(month>=6&&month<=8)return"summer";if(month>=9&&month<=11)return"fall";return"winter"}
export function suggestionsForSeason(season:Season):InspirationSuggestion[]{return SEASONAL_INSPIRATION.filter(item=>item.season===season)}
