import { after, before, test } from "node:test";
import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { createServer } from "vite";
import { readFile } from "node:fs/promises";

let server,shelf,launcher,intents,filters,catalog;
before(async()=>{server=await createServer({server:{middlewareMode:true},appType:"custom",logLevel:"silent"});shelf=await server.ssrLoadModule("/src/v2/InspirationShelf.tsx");launcher=await server.ssrLoadModule("/src/v2/InspirationLauncher.tsx");intents=await server.ssrLoadModule("/src/v2/inspirationIntents.ts");filters=await server.ssrLoadModule("/src/v2/inspirationFilters.ts");catalog=await server.ssrLoadModule("/src/features/templates/inspirationCatalog.ts")});
after(async()=>server?.close());
const categories=[{id:"date-night",emoji:"❤️",label:"Date Night",accent:"x"},{id:"restaurants",emoji:"🍽️",label:"Restaurants",accent:"x"}];
const space=(templateId="couple")=>({id:"s",name:"Together",emoji:"✨",type:templateId,ownerId:"u",adminIds:[],memberIds:["u"],memberNames:{u:"You"},categories,reactionDefs:[],templateId});
const shelfProps={space:space(),recentIdeaTemplateIds:[],onExplore(){},onSelect(){}};

test("Home renders one compact Inspiration entry point and no suggestions",()=>{const markup=renderToStaticMarkup(React.createElement(shelf.InspirationShelf,shelfProps));assert.match(markup,/Need inspiration\?/);assert.match(markup,/Discover something worth planning/);assert.match(markup,/Get Inspired/);assert.doesNotMatch(markup,/inspiration-card/);assert.doesNotMatch(markup,/Explore all ideas/);assert.doesNotMatch(markup,/<img/)});
test("Home entry lazy-loads the launcher instead of importing the catalog",async()=>{const source=await readFile("src/v2/InspirationShelf.tsx","utf8");assert.match(source,/lazy\(\(\)=>import\("\.\/InspirationLauncher"\)/);assert.doesNotMatch(source,/INSPIRATION_CATALOG/);assert.doesNotMatch(source,/inspirationItems/)});
test("launcher exposes an accessible dialog and all intent choices",()=>{const ref={current:null};const markup=renderToStaticMarkup(React.createElement(launcher.InspirationLauncher,{space:space(),recentIdeaTemplateIds:[],onClose(){},onExplore(){},onSelect(){},returnFocusRef:ref}));assert.match(markup,/role="dialog"/);assert.match(markup,/aria-modal="true"/);assert.match(markup,/What are you looking for today\?/);assert.match(markup,/aria-label="Close Inspiration"/);for(const intent of intents.INSPIRATION_INTENTS)assert.ok(markup.includes(intent.label.replaceAll("&","&amp;")),intent.label)});
test("Space templates receive the requested intent ordering",()=>{const order=templateId=>intents.orderInspirationIntents({spaceTemplateId:templateId,categories:[],recentIdeaTemplateIds:[]}).slice(0,5).map(item=>item.id);assert.deepEqual(order("couple"),["date-night","food-drinks","weekend","travel","stay-in"]);assert.deepEqual(order("travel"),["travel","outdoors","food-drinks","weekend","something-new"]);assert.deepEqual(order("gaming"),["games","stay-in","entertainment","food-drinks","weekend"]);assert.deepEqual(order("family"),["weekend","food-drinks","travel","outdoors","budget-friendly"]);assert.deepEqual(order("adventure"),["outdoors","something-new","weekend","travel","budget-friendly"]);assert.deepEqual(order("blank"),intents.INSPIRATION_INTENTS.slice(0,5).map(item=>item.id))});
test("categories and recent Idea templates safely influence non-destructive ordering",()=>{const ordered=intents.orderInspirationIntents({spaceTemplateId:"blank",categories,recentIdeaTemplateIds:["game"]});assert.ok(ordered.findIndex(item=>item.id==="games")<8);assert.ok(ordered.findIndex(item=>item.id==="date-night")<8)});
test("Surprise Me prefers the current Space and avoids the previous result",()=>{const first=intents.chooseSurpriseSuggestion(catalog.INSPIRATION_CATALOG,"gaming",null,()=>0);const second=intents.chooseSurpriseSuggestion(catalog.INSPIRATION_CATALOG,"gaming",first.id,()=>0);assert.ok(first.spaceTemplateIds.includes("gaming"));assert.ok(second.spaceTemplateIds.includes("gaming"));assert.notEqual(second.id,first.id)});
test("every launcher filter returns a usable collection",()=>{for(const intent of intents.INSPIRATION_INTENTS){if(!intent.filter)continue;assert.ok(filters.inspirationItems(catalog.INSPIRATION_CATALOG,intent.filter,"couple").length,intent.id)}});
test("full Inspiration becomes a history-aware Home subview and drafts remain explicit",async()=>{const source=await readFile("src/v2/AppV2.tsx","utf8");assert.match(source,/history\.pushState\([^;]+sidequestInspiration/);assert.match(source,/FullInspirationView space=\{space\}/);assert.match(source,/setIdeaSeed\(suggestion\);setIdeaTemplateId\(suggestion\.templateId\);setModal\("idea"\)/);assert.match(source,/seed\?\.prefill\?\.title/);assert.match(source,/resolveIdeaCategory\(initialTemplateId,space\.categories\)/)});
test("launcher manages Escape, focus, and scroll lock without wheel interception",async()=>{const source=await readFile("src/v2/InspirationLauncher.tsx","utf8");assert.match(source,/event\.key==="Escape"/);assert.match(source,/returnFocusRef\.current\?\.focus/);assert.match(source,/document\.documentElement\.style\.overflow="hidden"/);assert.match(source,/previousContentOverflow/);assert.doesNotMatch(source,/onWheel|preventDefault\(\).*wheel/i)});