import{addDoc,arrayUnion,collection,deleteDoc,doc,getDocs,limit,onSnapshot,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,type Unsubscribe}from"firebase/firestore";
import{deleteObject,getDownloadURL,ref,uploadBytesResumable}from"firebase/storage";
import{db,storage}from"../firebase";
import{compressImage}from"./images";
import{retry,withTimeout}from"./reliability";
import type{ActivityItem,Comment,Idea,Memory,Plan,Reaction,Reflection,Space}from"./domain";
const item=<T>(snap:{id:string;data:()=>unknown})=>({id:snap.id,...(snap.data()as object)})as T;
const normalizeSpace=(value:Space):Space=>({...value,adminIds:value.adminIds||[],memberNames:value.memberNames||Object.fromEntries(value.memberIds.map((id,index)=>[id,index===0?"Owner":"Member"]))});
const stamp=(value:unknown)=>value&&typeof value==="object"&&"toMillis"in value?(value as Timestamp).toMillis():0;
export function watchSpaces(uid:string,next:(items:Space[])=>void,error:(e:Error)=>void):Unsubscribe{return onSnapshot(query(collection(db,"spaces"),where("memberIds","array-contains",uid)),snapshot=>next(snapshot.docs.map(d=>normalizeSpace(item<Space>(d))).sort((a,b)=>stamp(b.updatedAt)-stamp(a.updatedAt))),error);}
export function watchIdeas(spaceId:string,next:(items:Idea[])=>void,error:(e:Error)=>void):Unsubscribe{return onSnapshot(query(collection(db,"ideas"),where("spaceId","==",spaceId)),snapshot=>next(snapshot.docs.map(d=>item<Idea>(d)).sort((a,b)=>stamp(b.createdAt)-stamp(a.createdAt))),error);}
export async function addSpace(input:Omit<Space,"id"|"createdAt"|"updatedAt">){return withTimeout(addDoc(collection(db,"spaces"),{...input,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}),15000,"Creating Space");}
export async function changeSpace(id:string,patch:Partial<Space>){return withTimeout(updateDoc(doc(db,"spaces",id),{...patch,updatedAt:serverTimestamp()}),15000,"Updating Space");}
export async function softDeleteSpace(id:string){const now=Date.now();return changeSpace(id,{deletedAt:Timestamp.fromMillis(now),purgeAfter:Timestamp.fromMillis(now+7*24*60*60*1000)});}
export async function restoreSpace(id:string){return changeSpace(id,{deletedAt:null,purgeAfter:null});}
export async function addIdea(input:Omit<Idea,"id"|"createdAt"|"updatedAt">){return withTimeout(addDoc(collection(db,"ideas"),{...input,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}),15000,"Saving Idea");}
export async function changeIdea(id:string,patch:Partial<Idea>){const clean:Record<string,unknown>=Object.fromEntries(Object.entries(patch).filter(([,v])=>v!==undefined));if(patch.completed===true&&!patch.completedAt)clean.completedAt=serverTimestamp();return withTimeout(updateDoc(doc(db,"ideas",id),{...clean,updatedAt:serverTimestamp()}),15000,"Updating Idea");}
export async function deleteIdea(id:string){return withTimeout(deleteDoc(doc(db,"ideas",id)),15000,"Deleting Idea");}
export function watchPlan(ideaId:string,next:(plan:Plan|null)=>void):Unsubscribe{return onSnapshot(doc(db,"plans",ideaId),snapshot=>next(snapshot.exists()?item<Plan>(snapshot):null));}
export async function savePlan(plan:Plan){const{id,...value}=plan;return withTimeout(setDoc(doc(db,"plans",id),{...value,updatedAt:serverTimestamp()},{merge:true}),15000,"Saving plan");}
export function watchMemory(ideaId:string,next:(memory:Memory|null)=>void):Unsubscribe{return onSnapshot(doc(db,"memories",ideaId),snapshot=>next(snapshot.exists()?item<Memory>(snapshot):null));}
export async function saveMemory(memory:Memory){const{id,...value}=memory;return withTimeout(setDoc(doc(db,"memories",id),{...value,updatedAt:serverTimestamp()},{merge:true}),15000,"Saving memory");}
export function watchReflections(ideaId:string,next:(items:Reflection[])=>void):Unsubscribe{return onSnapshot(collection(db,"memories",ideaId,"reflections"),snapshot=>next(snapshot.docs.map(d=>item<Reflection>(d))));}
export async function saveReflection(ideaId:string,value:Reflection){const{id,...data}=value;return withTimeout(setDoc(doc(db,"memories",ideaId,"reflections",id),{...data,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true}),15000,"Saving reflection");}
export function watchComments(ideaId:string,next:(items:Comment[])=>void):Unsubscribe{return onSnapshot(collection(db,"ideas",ideaId,"comments"),snapshot=>next(snapshot.docs.map(d=>item<Comment>(d)).sort((a,b)=>stamp(a.createdAt)-stamp(b.createdAt))));}
export async function addComment(ideaId:string,value:Omit<Comment,"id"|"createdAt">){return withTimeout(addDoc(collection(db,"ideas",ideaId,"comments"),{...value,createdAt:serverTimestamp()}),15000,"Sending comment");}
export function watchReactions(ideaId:string,next:(items:Reaction[])=>void):Unsubscribe{return onSnapshot(collection(db,"ideas",ideaId,"reactions"),snapshot=>next(snapshot.docs.map(d=>item<Reaction>(d))));}
export async function react(ideaId:string,value:Reaction|null,uid:string){const target=doc(db,"ideas",ideaId,"reactions",uid);return value?withTimeout(setDoc(target,{...value,updatedAt:serverTimestamp()}),15000,"Saving reaction"):deleteDoc(target);}
export function watchActivity(spaceIds:string[],next:(items:ActivityItem[])=>void):Unsubscribe{if(!spaceIds.length){next([]);return()=>undefined;}return onSnapshot(query(collection(db,"activity"),where("spaceId","in",spaceIds.slice(0,10)),limit(50)),snapshot=>next(snapshot.docs.map(d=>item<ActivityItem>(d)).sort((a,b)=>stamp(b.createdAt)-stamp(a.createdAt))));}
export async function activity(value:Omit<ActivityItem,"id"|"createdAt">){return retry(()=>addDoc(collection(db,"activity"),{...value,createdAt:serverTimestamp()}),2);}
export async function invite(space:Space,uid:string){const code=crypto.randomUUID().slice(0,8).toUpperCase();await addDoc(collection(db,"invitations"),{code,spaceId:space.id,spaceName:space.name,spaceEmoji:space.emoji,invitedBy:uid,createdAt:serverTimestamp()});return code;}
export async function join(code:string,uid:string,name:string){const result=await getDocs(query(collection(db,"invitations"),where("code","==",code.trim().toUpperCase()),limit(1)));if(result.empty)throw new Error("Invitation code not found.");const inviteData=result.docs[0].data();await updateDoc(doc(db,"spaces",inviteData.spaceId),{memberIds:arrayUnion(uid),[`memberNames.${uid}`]:name,updatedAt:serverTimestamp()});}
export async function uploadImage(spaceId:string,kind:"ideas"|"memories",ownerId:string,file:File,onProgress:(value:number)=>void){const compressed=await compressImage(file);const path=`spaces/${spaceId}/${kind}/${ownerId}/${crypto.randomUUID()}.jpg`;const task=uploadBytesResumable(ref(storage,path),compressed,{contentType:"image/jpeg"});return new Promise<string>((resolve,reject)=>task.on("state_changed",snapshot=>onProgress(Math.round(snapshot.bytesTransferred/snapshot.totalBytes*100)),reject,async()=>resolve(await getDownloadURL(task.snapshot.ref))));}
export async function removeImage(url:string){if(!url)return;try{await deleteObject(ref(storage,url));}catch{/* Replaced images are best-effort cleanup. */}}
