import{addDoc,arrayUnion,collection,deleteDoc,doc,getDoc,limit,onSnapshot,query,runTransaction,serverTimestamp,setDoc,Timestamp,updateDoc,where,writeBatch,type Unsubscribe}from"firebase/firestore";
import{deleteObject,getDownloadURL,ref,uploadBytesResumable}from"firebase/storage";
import{db,storage}from"../firebase";
import{compressImage}from"./images";
import{retry,withTimeout}from"./reliability";
import type{ActivityItem,Comment,Idea,Memory,Plan,Reaction,Reflection,Space}from"./domain";
const item=<T>(snap:{id:string;data:()=>unknown})=>({id:snap.id,...(snap.data()as object)})as T;
const normalizeSpace=(value:Space):Space=>({...value,adminIds:value.adminIds||[],memberNames:value.memberNames||Object.fromEntries(value.memberIds.map((id,index)=>[id,index===0?"Owner":"Member"]))});
const stamp=(value:unknown)=>value&&typeof value==="object"&&"toMillis"in value?(value as Timestamp).toMillis():0;
export function watchSpaces(uid:string,next:(items:Space[])=>void,error:(e:Error)=>void):Unsubscribe{return onSnapshot(query(collection(db,"spaces"),where("memberIds","array-contains",uid)),snapshot=>next(snapshot.docs.map(d=>normalizeSpace(item<Space>(d))).sort((a,b)=>stamp(b.updatedAt)-stamp(a.updatedAt))),error);}
export function watchIdeas(spaceId:string,next:(items:Idea[])=>void,error:(e:Error)=>void):Unsubscribe{return onSnapshot(query(collection(db,"ideas"),where("spaceId","==",spaceId)),snapshot=>next(snapshot.docs.map(d=>item<Idea>(d)).sort((a,b)=>stamp(b.createdAt)-stamp(a.createdAt))),error);}
export async function addSpace(input:Omit<Space,"id"|"createdAt"|"updatedAt">){return withTimeout(addDoc(collection(db,"spaces"),{...input,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}),15000,"Creating Space");}
export async function changeSpace(id:string,patch:Partial<Space>){return withTimeout(updateDoc(doc(db,"spaces",id),{...patch,updatedAt:serverTimestamp()}),15000,"Updating Space");}
export async function syncMemberIdentity(spaceId:string,uid:string,displayName:string){return retry(()=>withTimeout(updateDoc(doc(db,"spaces",spaceId),{["memberNames."+uid]:displayName,updatedAt:serverTimestamp()}),15000,"Updating member profile"),3);}
export async function softDeleteSpace(id:string){const now=Date.now();return changeSpace(id,{deletedAt:Timestamp.fromMillis(now),purgeAfter:Timestamp.fromMillis(now+7*24*60*60*1000)});}
export async function restoreSpace(id:string){return changeSpace(id,{deletedAt:null,purgeAfter:null});}
export async function addIdea(input:Omit<Idea,"id"|"createdAt"|"updatedAt">,id:string=crypto.randomUUID()){const reference=doc(db,"ideas",id);await withTimeout(setDoc(reference,{...input,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}),15000,"Saving Idea");return{id};}
export async function changeIdea(id:string,patch:Partial<Idea>){const clean:Record<string,unknown>=Object.fromEntries(Object.entries(patch).filter(([,v])=>v!==undefined));if(patch.completed===true&&!patch.completedAt)clean.completedAt=serverTimestamp();return withTimeout(updateDoc(doc(db,"ideas",id),{...clean,updatedAt:serverTimestamp()}),15000,"Updating Idea");}
export async function deleteIdea(id:string){return withTimeout(deleteDoc(doc(db,"ideas",id)),15000,"Deleting Idea");}
export function watchPlan(ideaId:string,next:(plan:Plan|null)=>void,error:(e:Error)=>void=()=>undefined):Unsubscribe{return onSnapshot(doc(db,"plans",ideaId),snapshot=>next(snapshot.exists()?item<Plan>(snapshot):null),error);}
export async function ensurePlan(plan:Plan){const reference=doc(db,"plans",plan.id);await withTimeout(runTransaction(db,async transaction=>{if((await transaction.get(reference)).exists())return;const{id,...value}=plan;transaction.set(reference,{...value,updatedAt:serverTimestamp()});}),15000,"Opening plan");}
export async function savePlan(plan:Plan){const reference=doc(db,"plans",plan.id);return withTimeout(runTransaction(db,async transaction=>{const current=await transaction.get(reference);if(!current.exists())throw new Error("This plan is no longer available.");const serverVersion=current.data().updatedAt as Timestamp|undefined;const localVersion=plan.updatedAt;if(serverVersion&&localVersion&&serverVersion.toMillis()!==localVersion.toMillis())throw new Error("Someone else updated this plan. Their latest changes are now shown; review yours and try again.");const{id,...value}=plan;transaction.set(reference,{...value,updatedAt:serverTimestamp()},{merge:true});}),15000,"Saving plan");}
export function watchMemory(ideaId:string,next:(memory:Memory|null)=>void,error:(e:Error)=>void=()=>undefined):Unsubscribe{return onSnapshot(doc(db,"memories",ideaId),snapshot=>next(snapshot.exists()?item<Memory>(snapshot):null),error);}
export async function ensureMemory(memory:Memory){const reference=doc(db,"memories",memory.id);await withTimeout(runTransaction(db,async transaction=>{if((await transaction.get(reference)).exists())return;const{id,...value}=memory;transaction.set(reference,{...value,updatedAt:serverTimestamp()});}),15000,"Opening memory");}
export async function saveMemory(memory:Memory){const reference=doc(db,"memories",memory.id);return withTimeout(runTransaction(db,async transaction=>{const current=await transaction.get(reference);if(!current.exists())throw new Error("This memory is no longer available.");const serverVersion=current.data().updatedAt as Timestamp|undefined;const localVersion=memory.updatedAt;if(serverVersion&&localVersion&&serverVersion.toMillis()!==localVersion.toMillis())throw new Error("Someone else updated this memory. Their latest changes are now shown; review yours and try again.");const{id,...value}=memory;transaction.set(reference,{...value,updatedAt:serverTimestamp()},{merge:true});}),15000,"Saving memory");}
export function watchReflections(ideaId:string,next:(items:Reflection[])=>void):Unsubscribe{return onSnapshot(collection(db,"memories",ideaId,"reflections"),snapshot=>next(snapshot.docs.map(d=>item<Reflection>(d))));}
export async function saveReflection(ideaId:string,value:Reflection){const{id,...data}=value;return withTimeout(setDoc(doc(db,"memories",ideaId,"reflections",id),{...data,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true}),15000,"Saving reflection");}
export function watchComments(ideaId:string,next:(items:Comment[])=>void):Unsubscribe{return onSnapshot(collection(db,"ideas",ideaId,"comments"),snapshot=>next(snapshot.docs.map(d=>item<Comment>(d)).sort((a,b)=>stamp(a.createdAt)-stamp(b.createdAt))));}
export async function addComment(ideaId:string,value:Omit<Comment,"id"|"createdAt">){return withTimeout(addDoc(collection(db,"ideas",ideaId,"comments"),{...value,createdAt:serverTimestamp()}),15000,"Sending comment");}
export function watchReactions(ideaId:string,next:(items:Reaction[])=>void):Unsubscribe{return onSnapshot(collection(db,"ideas",ideaId,"reactions"),snapshot=>next(snapshot.docs.map(d=>item<Reaction>(d))));}
export async function react(ideaId:string,value:Reaction|null,uid:string){const target=doc(db,"ideas",ideaId,"reactions",uid);return value?withTimeout(setDoc(target,{...value,updatedAt:serverTimestamp()}),15000,"Saving reaction"):deleteDoc(target);}
export function watchActivity(spaceIds:string[],next:(items:ActivityItem[])=>void):Unsubscribe{if(!spaceIds.length){next([]);return()=>undefined;}return onSnapshot(query(collection(db,"activity"),where("spaceId","in",spaceIds.slice(0,10)),limit(50)),snapshot=>next(snapshot.docs.map(d=>item<ActivityItem>(d)).sort((a,b)=>stamp(b.createdAt)-stamp(a.createdAt))));}
export async function activity(value:Omit<ActivityItem,"id"|"createdAt">){return retry(()=>addDoc(collection(db,"activity"),{...value,createdAt:serverTimestamp()}),2);}
export async function invite(space:Space,uid:string){const code=crypto.randomUUID().replace(/-/g,"").slice(0,12).toUpperCase();await withTimeout(setDoc(doc(db,"invitations",code),{code,spaceId:space.id,spaceName:space.name,spaceEmoji:space.emoji,invitedBy:uid,createdAt:serverTimestamp(),expiresAt:Timestamp.fromMillis(Date.now()+7*24*60*60*1000)}),15000,"Creating invite");return code;}
export async function join(code:string,uid:string,name:string){const normalized=code.trim().toUpperCase();if(!normalized)throw new Error("Enter an invitation code.");const invitation=await withTimeout(getDoc(doc(db,"invitations",normalized)),15000,"Checking invite");if(!invitation.exists())throw new Error("This invitation is invalid or has expired.");const inviteData=invitation.data();const expiresAt=inviteData.expiresAt as Timestamp|undefined;if(!expiresAt||expiresAt.toMillis()<=Date.now())throw new Error("This invitation has expired. Ask the Space owner for a new one.");const batch=writeBatch(db);batch.set(doc(db,"spaces",inviteData.spaceId,"joinClaims",uid),{uid,code:normalized,createdAt:serverTimestamp()});const membership:Record<string,unknown>={memberIds:arrayUnion(uid),updatedAt:serverTimestamp()};membership["memberNames."+uid]=name;batch.update(doc(db,"spaces",inviteData.spaceId),membership);try{await withTimeout(batch.commit(),15000,"Joining Space")}catch(error){try{const existing=await getDoc(doc(db,"spaces",inviteData.spaceId));if(existing.exists()&&(existing.data().memberIds||[]).includes(uid))return}catch{/* A non-member cannot read the Space yet. */}throw error}}
export async function uploadImage(spaceId:string,kind:"ideas"|"memories",ownerId:string,userId:string,file:File,onProgress:(value:number)=>void){const compressed=await compressImage(file);const path="spaces/"+spaceId+"/"+kind+"/"+ownerId+"/"+userId+"/"+crypto.randomUUID()+".jpg";const task=uploadBytesResumable(ref(storage,path),compressed,{contentType:"image/jpeg"});return new Promise<string>((resolve,reject)=>{const timer=setTimeout(()=>{task.cancel();reject(new Error("Image upload timed out. Check your connection and try again."))},45000);task.on("state_changed",snapshot=>onProgress(Math.round(snapshot.bytesTransferred/snapshot.totalBytes*100)),error=>{clearTimeout(timer);reject(error)},async()=>{clearTimeout(timer);try{resolve(await getDownloadURL(task.snapshot.ref))}catch(error){reject(error)}})})}
export async function removeImage(url:string){if(!url)return;try{await deleteObject(ref(storage,url));}catch{/* Replaced images are best-effort cleanup. */}}
