import { ArrowUpRight, CalendarDays, DollarSign, MapPin, Ticket, Users } from "lucide-react";
import { getIdeaTemplateDefinition } from "../features/templates/ideaTemplates";
import { resolveIdeaTemplateId, sanitizeTemplateData } from "../features/templates/templateValidation";
import type { IdeaTemplateId } from "../features/templates/templateTypes";
import { questTypeDefinition, resolveQuestType } from "../features/quests/questTypes";
import { measurableGoal, momentumSignals } from "../features/living-quests/livingQuests";
import type { UserProfile } from "../types/domain";
import type { ActivityItem, Idea, Space } from "./domain";
import "./idea-cards.css";

export interface IdeaCardMetadata{key:string;label:string;value:string;icon:"location"|"money"|"calendar"|"ticket"|"people"}
const ICONS={location:MapPin,money:DollarSign,calendar:CalendarDays,ticket:Ticket,people:Users};
const map=(value:unknown):{[key:string]:unknown}=>typeof value==="object"&&value!==null&&!Array.isArray(value)?value as{[key:string]:unknown}:{};
const text=(value:unknown):string=>typeof value==="string"?value:typeof value==="number"?String(value):"";
const list=(value:unknown):string=>Array.isArray(value)?value.filter(item=>typeof item==="string").join(", "):"";
const money=(value:unknown):string=>typeof value==="number"?`$${value.toLocaleString()}`:text(value);
export function ideaCardMetadata(idea:Pick<Idea,"templateId"|"templateVersion"|"templateData"|"location">):IdeaCardMetadata[]{const templateId=resolveIdeaTemplateId(idea),data=map(sanitizeTemplateData(templateId,idea.templateData)),location=idea.location?.trim(),values:IdeaCardMetadata[]=[];const add=(key:string,label:string,value:string,icon:IdeaCardMetadata["icon"])=>{if(value)values.push({key,label,value,icon})};if(templateId==="restaurant"){add("cuisine","Cuisine",text(data.cuisine),"ticket");add("price","Price range",text(data.priceRange),"money");add("location","Location",location,"location")}else if(templateId==="movie"){add("genre","Genre",text(data.genre),"ticket");add("runtime","Runtime",data.runtimeMinutes?`${data.runtimeMinutes} min`:"","calendar");add("streaming","Streaming service",text(data.streamingService),"ticket")}else if(templateId==="trip"){add("destination","Destination",text(data.destination)||location,"location");add("dates","Potential dates",list(data.potentialDates),"calendar");add("budget","Budget goal",money(data.budgetGoal),"money")}else if(templateId==="hike"){add("difficulty","Difficulty",text(data.difficulty),"ticket");add("distance","Distance",data.distanceMiles?`${data.distanceMiles} mi`:"","location");add("location","Location",location||text(data.trailName),"location")}else if(templateId==="event"){add("date","Event date",text(data.eventDate),"calendar");add("venue","Venue",text(data.venue)||location,"location")}else if(templateId==="gift"){add("recipient","Recipient",text(data.recipient),"people");add("occasion","Occasion",text(data.occasion),"calendar");add("price","Estimated price",money(data.estimatedPrice),"money")}else if(templateId==="hotel"){add("location","Location",location,"location");add("nightly","Nightly estimate",money(data.nightlyEstimate),"money");add("dates","Preferred dates",list(data.preferredDates),"calendar")}else if(templateId==="game"){add("platform","Platform",text(data.platform),"ticket");add("players","Player count",data.playerCount?`${data.playerCount} players`:"","people")}else if(location)add("location","Location",location,"location");return values.slice(0,3)}
export function ideaCardContext(idea:Idea,space:Space,profile:UserProfile):string{if(idea.completed)return"A memory now";if(space.memberIds.length===1)return"A Quest of your own";if(idea.createdBy!==profile.id)return`Shared by ${idea.createdByName}`;const waiting=space.memberIds.filter(id=>id!==profile.id).map(id=>space.memberNames[id]||"someone")[0];return`Still waiting on ${waiting||"your people"}`}
export function IdeaCard({idea,space,profile,onOpen,variant="standard",events=[]}:{idea:Idea;space:Space;profile:UserProfile;onOpen:()=>void;variant?:"standard"|"compact";events?:ActivityItem[]}){const templateId:IdeaTemplateId=resolveIdeaTemplateId(idea),template=getIdeaTemplateDefinition(templateId),metadata=ideaCardMetadata(idea),questType=questTypeDefinition(idea.questType),resolvedType=resolveQuestType(idea.questType),goal=measurableGoal(idea),momentum=momentumSignals(idea,events,space)[0],isCollection=resolvedType==="collection",isChapter=isCollection&&idea.chapterMode===true,kind=idea.completed?"memory":isChapter?"chapter":isCollection?"collection":goal?"goal":"quest";return <button className={`card idea-card living-card ${variant} ${kind}-card template-${templateId}${idea.photoUrl?" has-image":" no-image"}`} onClick={onOpen} aria-label={`Open ${idea.title}. ${idea.completed?"Memory":isChapter?"Life Chapter":isCollection?"Collection":questType.label+" Quest"}.`}>
  <div className="cover">{idea.photoUrl&&<img src={idea.photoUrl} alt="" loading={variant==="compact"?"lazy":"eager"} decoding="async"/>}<div className="cover-shade"/>{!idea.photoUrl&&<span className="idea-card-fallback" aria-hidden="true">{isCollection?"📖":template.emoji}</span>}<span className="space-mark" aria-label={`Space: ${space.name}`}>{space.emoji}</span><div className="idea-card-title"><small>{idea.completed?"Memory":isChapter?"Chapter":isCollection?"Collection":goal?"Goal":questType.label}</small><h2>{idea.title}</h2></div></div>
  <div className="living-card-story"><div className="card-people" aria-label={`Shared with ${space.memberIds.length} ${space.memberIds.length===1?"person":"people"}`}>{space.memberIds.slice(0,3).map(id=><i key={id} title={space.memberNames[id]||"Member"}>{(space.memberNames[id]||"M")[0]?.toUpperCase()}</i>)}</div><p>{ideaCardContext(idea,space,profile)}</p>{goal?<div className="living-goal-progress"><div><span>{goal.current} / {goal.target} {goal.unit}</span><b>{goal.percentage}%</b></div><progress value={Math.min(goal.current,goal.target)} max={goal.target}>{goal.percentage}%</progress>{goal.nextThreshold&&<small>Next: {goal.nextThreshold} {goal.unit}</small>}</div>:<p className="card-momentum">{idea.completed?(idea.description||"A moment worth returning to."):isCollection?(idea.description||"Experiences that belong together."):momentum.label}</p>}{!goal&&metadata.length>0&&<div className="card-contexts">{metadata.map(item=>{const Icon=ICONS[item.icon];return <span className="card-context" key={item.key}><Icon aria-hidden="true"/>{item.value}</span>})}</div>}<span className="card-open" aria-hidden="true"><ArrowUpRight/></span></div>
</button>}
