import { Check, ChevronDown, Clock3, Sparkles } from "lucide-react";
import "./version-history.css";

export const VERSION_04_DEPLOYED=true;
export interface VersionEntry{version:string;title:string;summary:string;details:readonly string[];status:"Past"|"Current"|"Coming Soon"|"Roadmap"}
export const VERSION_HISTORY:readonly VersionEntry[]=[
  {version:"0.1",title:"Foundation",status:"Past",summary:"Created the SideQuest concept, designed the complete product in Figma, established the core feature set and user flows, and validated the vision through an interactive prototype.",details:["Complete Figma UI/UX","Product concept and mission","Core screen architecture","Spaces, Ideas, Planner, Maps, Memories, and Activity concepts","Interactive prototype","Flow and dead-end validation"]},
  {version:"0.2",title:"Functional Application",status:"Past",summary:"Rebuilt SideQuest as a real web application using React, Vite, Node.js, and Firebase, transforming the prototype into a functional multi-user platform.",details:["Firebase Authentication","Firestore and Storage","Multi-user Spaces","Invitations and ownership","Ideas, comments, and reactions","Planner","Map","Memories","Activity","Profiles and notifications","Responsive web app","Production deployment"]},
  {version:"0.3",title:"Beta Readiness",status:VERSION_04_DEPLOYED?"Past":"Current",summary:"Refined the product through a complete UI overhaul, onboarding, Help & Learn, accessibility improvements, security hardening, testing, and production optimization.",details:["Sunlit Scrapbook overhaul","Onboarding","Help & Learn","Contextual tips","Accessibility","Responsive refinements","Firestore and Storage security","Invite hardening","Duplicate prevention","Error and loading states","Emulator and browser testing","Production verification"]},
  {version:"0.4",title:"Inspiration Update",status:VERSION_04_DEPLOYED?"Current":"Coming Soon",summary:"Introduces templates, starter content, dynamic Idea experiences, and inspiration so users never have to start from a blank page.",details:["Space templates","Category packs","Optional starter Ideas","Idea templates","Dynamic cards","Dynamic detail layouts","Inspiration catalog","Seasonal Inspiration"]},
  {version:"0.5",title:"Real-World Beta",status:"Roadmap",summary:"Broader real-user learning and reliability refinement.",details:["Broader user testing","Product feedback","Reliability fixes","Usability refinements","Performance optimization"]},
  {version:"0.6",title:"Retention & Smart Suggestions",status:"Roadmap",summary:"Helpful ways to return to possibilities at the right time.",details:["Weekly inspiration","Resurfaced Ideas","Reminders","Smarter recommendations","Better search and discovery"]},
  {version:"0.7",title:"Expansion",status:"Roadmap",summary:"More ways for a Space to reflect the people and plans inside it.",details:["More Space personalities","Deeper customization","Broader planning use cases","Advanced organization"]},
  {version:"0.8",title:"Native Experience",status:"Roadmap",summary:"A more deeply integrated mobile experience.",details:["iOS","Android","Push notifications","Widgets","Offline support","Native sharing and uploads"]},
  {version:"0.9",title:"Growth",status:"Roadmap",summary:"Improved discovery and thoughtful ways to invite more people.",details:["Referrals","Improved invitations","Discovery","Marketing-site improvements","Creator and community outreach"]},
  {version:"1.0",title:"Public Launch",status:"Roadmap",summary:"A stable, polished SideQuest ready for public availability.",details:["Polished native and web experience","Reliable infrastructure","Excellent onboarding","Stable collaboration","Public availability"]}
];

export function VersionHistory(){return <section className="version-history" aria-labelledby="version-history-title"><header><div><p className="eyebrow">Version History</p><h3 id="version-history-title">How SideQuest is growing</h3><p>What has shipped, what is being prepared, and what remains an honest roadmap.</p></div><Sparkles aria-hidden="true"/></header><div>{VERSION_HISTORY.map(entry=><details key={entry.version} className={`version-entry status-${entry.status.toLowerCase().replace(" ","-")}`} open={entry.status==="Current"||entry.status==="Coming Soon"}><summary><span className="version-marker" aria-hidden="true">{entry.status==="Past"?<Check/>:<Clock3/>}</span><span><small>Version {entry.version}</small><b>{entry.title}</b></span><em>{entry.status}</em><ChevronDown aria-hidden="true"/></summary><div><p>{entry.summary}</p><ul>{entry.details.map(detail=><li key={detail}>{detail}</li>)}</ul></div></details>)}</div></section>}
